#!/usr/bin/env python3

import interpreter
import argparse

def main():
    args = parse_arguments()
    interpreter.run_file(args.program)

def parse_arguments():
    parser = argparse.ArgumentParser(description='fpl interpreter')
    parser.add_argument('program', action='store', help='fpl script to run')
    args = parser.parse_args()
    return args

if __name__ == '__main__':
    main()
