#!/usr/bin/env python3

import program

import argparse
import sys

def main():
    args = parse_arguments()
    prog = program.Program()
    if args.program:
        prog.run_file(args.program)
    elif args.command:
        prog.run_code(args.command)
    else:
        for line in sys.stdin:
            prog.run_code(line)

def parse_arguments():
    parser = argparse.ArgumentParser(description='fpl interpreter')
    parser.add_argument(
            'program', nargs='?',
            help='fpl script to run')
    parser.add_argument(
            '-c', '--command',
            help='run a script from the command line')
    args = parser.parse_args()
    return args

if __name__ == '__main__':
    main()
